// Masculine ↔ Feminine flashcard pairs per lesson.
// Each pair: m = masculine form, f = feminine form, en = English meaning, kind = 'noun' | 'adj'.
export interface GenderPair {
  m: string;
  f: string;
  en: string;
  kind: "noun" | "adj";
}

export const TAXI_GENDER: Record<string, GenderPair[]> = {
  // ============ UNIT 1 ============
  "1-1": [
    { m: "un ami", f: "une amie", en: "a friend", kind: "noun" },
    { m: "un monsieur", f: "une dame", en: "a gentleman / a lady", kind: "noun" },
    { m: "un étudiant", f: "une étudiante", en: "a student", kind: "noun" },
    { m: "un professeur", f: "une professeure", en: "a teacher", kind: "noun" },
    { m: "enchanté", f: "enchantée", en: "delighted", kind: "adj" },
    { m: "français", f: "française", en: "French", kind: "adj" },
    { m: "un voisin", f: "une voisine", en: "a neighbour", kind: "noun" },
    { m: "petit", f: "petite", en: "small", kind: "adj" },
  ],
  "1-2": [
    { m: "un acteur", f: "une actrice", en: "an actor", kind: "noun" },
    { m: "un chanteur", f: "une chanteuse", en: "a singer", kind: "noun" },
    { m: "un Italien", f: "une Italienne", en: "an Italian", kind: "noun" },
    { m: "un Espagnol", f: "une Espagnole", en: "a Spaniard", kind: "noun" },
    { m: "américain", f: "américaine", en: "American", kind: "adj" },
    { m: "anglais", f: "anglaise", en: "English", kind: "adj" },
    { m: "japonais", f: "japonaise", en: "Japanese", kind: "adj" },
    { m: "allemand", f: "allemande", en: "German", kind: "adj" },
  ],
  "1-3": [
    { m: "un copain", f: "une copine", en: "a buddy / pal", kind: "noun" },
    { m: "un collègue", f: "une collègue", en: "a colleague", kind: "noun" },
    { m: "un voisin", f: "une voisine", en: "a neighbour", kind: "noun" },
    { m: "fatigué", f: "fatiguée", en: "tired", kind: "adj" },
    { m: "content", f: "contente", en: "happy", kind: "adj" },
    { m: "occupé", f: "occupée", en: "busy", kind: "adj" },
    { m: "malade", f: "malade", en: "sick (same form)", kind: "adj" },
    { m: "marié", f: "mariée", en: "married", kind: "adj" },
  ],
  "1-4": [
    { m: "un internaute", f: "une internaute", en: "an internet user", kind: "noun" },
    { m: "un employé", f: "une employée", en: "an employee", kind: "noun" },
    { m: "un journaliste", f: "une journaliste", en: "a journalist", kind: "noun" },
    { m: "un musicien", f: "une musicienne", en: "a musician", kind: "noun" },
    { m: "marocain", f: "marocaine", en: "Moroccan", kind: "adj" },
    { m: "chinois", f: "chinoise", en: "Chinese", kind: "adj" },
    { m: "célibataire", f: "célibataire", en: "single", kind: "adj" },
    { m: "sympathique", f: "sympathique", en: "friendly", kind: "adj" },
  ],
  // ============ UNIT 2 ============
  "2-5": [
    { m: "un livre", f: "une table", en: "a book / a table", kind: "noun" },
    { m: "un stylo", f: "une trousse", en: "a pen / a pencil case", kind: "noun" },
    { m: "un sac", f: "une valise", en: "a bag / a suitcase", kind: "noun" },
    { m: "un téléphone", f: "une clé", en: "a phone / a key", kind: "noun" },
    { m: "un ordinateur", f: "une montre", en: "a computer / a watch", kind: "noun" },
    { m: "noir", f: "noire", en: "black", kind: "adj" },
    { m: "blanc", f: "blanche", en: "white", kind: "adj" },
    { m: "bleu", f: "bleue", en: "blue", kind: "adj" },
  ],
  "2-6": [
    { m: "un homme", f: "une femme", en: "a man / a woman", kind: "noun" },
    { m: "un garçon", f: "une fille", en: "a boy / a girl", kind: "noun" },
    { m: "grand", f: "grande", en: "tall / big", kind: "adj" },
    { m: "petit", f: "petite", en: "small", kind: "adj" },
    { m: "blond", f: "blonde", en: "blond", kind: "adj" },
    { m: "brun", f: "brune", en: "brown-haired", kind: "adj" },
    { m: "beau", f: "belle", en: "handsome / beautiful", kind: "adj" },
    { m: "vieux", f: "vieille", en: "old", kind: "adj" },
    { m: "jeune", f: "jeune", en: "young (same form)", kind: "adj" },
    { m: "sportif", f: "sportive", en: "athletic", kind: "adj" },
  ],
  "2-7": [
    { m: "un vendeur", f: "une vendeuse", en: "a salesperson", kind: "noun" },
    { m: "un client", f: "une cliente", en: "a customer", kind: "noun" },
    { m: "un pull", f: "une chemise", en: "a sweater / a shirt", kind: "noun" },
    { m: "un pantalon", f: "une jupe", en: "trousers / a skirt", kind: "noun" },
    { m: "un manteau", f: "une veste", en: "a coat / a jacket", kind: "noun" },
    { m: "cher", f: "chère", en: "expensive / dear", kind: "adj" },
    { m: "joli", f: "jolie", en: "pretty", kind: "adj" },
    { m: "nouveau", f: "nouvelle", en: "new", kind: "adj" },
  ],
  "2-8": [
    { m: "un peintre", f: "une peintre", en: "a painter", kind: "noun" },
    { m: "un sculpteur", f: "une sculptrice", en: "a sculptor", kind: "noun" },
    { m: "un artiste", f: "une artiste", en: "an artist", kind: "noun" },
    { m: "un écrivain", f: "une écrivaine", en: "a writer", kind: "noun" },
    { m: "un tableau", f: "une œuvre", en: "a painting / a work", kind: "noun" },
    { m: "créatif", f: "créative", en: "creative", kind: "adj" },
    { m: "célèbre", f: "célèbre", en: "famous", kind: "adj" },
    { m: "original", f: "originale", en: "original", kind: "adj" },
  ],
  // ============ UNIT 3 ============
  "3-9": [
    { m: "un appartement", f: "une maison", en: "an apartment / a house", kind: "noun" },
    { m: "un salon", f: "une cuisine", en: "a living room / a kitchen", kind: "noun" },
    { m: "un balcon", f: "une terrasse", en: "a balcony / a terrace", kind: "noun" },
    { m: "un canapé", f: "une chaise", en: "a sofa / a chair", kind: "noun" },
    { m: "un lit", f: "une armoire", en: "a bed / a wardrobe", kind: "noun" },
    { m: "lumineux", f: "lumineuse", en: "bright (light)", kind: "adj" },
    { m: "spacieux", f: "spacieuse", en: "spacious", kind: "adj" },
    { m: "moderne", f: "moderne", en: "modern", kind: "adj" },
  ],
  "3-10": [
    { m: "un boulevard", f: "une avenue", en: "a boulevard / an avenue", kind: "noun" },
    { m: "un pont", f: "une rue", en: "a bridge / a street", kind: "noun" },
    { m: "un musée", f: "une église", en: "a museum / a church", kind: "noun" },
    { m: "un café", f: "une boulangerie", en: "a café / a bakery", kind: "noun" },
    { m: "un passant", f: "une passante", en: "a passer-by", kind: "noun" },
    { m: "premier", f: "première", en: "first", kind: "adj" },
    { m: "dernier", f: "dernière", en: "last", kind: "adj" },
    { m: "loin", f: "loin", en: "far (adverb)", kind: "adj" },
  ],
  "3-11": [
    { m: "un voyageur", f: "une voyageuse", en: "a traveller", kind: "noun" },
    { m: "un passager", f: "une passagère", en: "a passenger", kind: "noun" },
    { m: "un billet", f: "une carte", en: "a ticket / a card", kind: "noun" },
    { m: "un train", f: "une voiture", en: "a train / a car", kind: "noun" },
    { m: "un avion", f: "une valise", en: "a plane / a suitcase", kind: "noun" },
    { m: "rapide", f: "rapide", en: "fast", kind: "adj" },
    { m: "long", f: "longue", en: "long", kind: "adj" },
    { m: "prêt", f: "prête", en: "ready", kind: "adj" },
  ],
  "3-12": [
    { m: "un quartier", f: "une ville", en: "a neighbourhood / a city", kind: "noun" },
    { m: "un port", f: "une plage", en: "a port / a beach", kind: "noun" },
    { m: "un marché", f: "une place", en: "a market / a square", kind: "noun" },
    { m: "un habitant", f: "une habitante", en: "an inhabitant", kind: "noun" },
    { m: "un Marseillais", f: "une Marseillaise", en: "someone from Marseille", kind: "noun" },
    { m: "ensoleillé", f: "ensoleillée", en: "sunny", kind: "adj" },
    { m: "animé", f: "animée", en: "lively", kind: "adj" },
    { m: "calme", f: "calme", en: "calm / quiet", kind: "adj" },
  ],
  // ============ UNIT 4 ============
  "4-13": [
    { m: "un film", f: "une chanson", en: "a film / a song", kind: "noun" },
    { m: "un acteur", f: "une actrice", en: "an actor", kind: "noun" },
    { m: "un chanteur", f: "une chanteuse", en: "a singer", kind: "noun" },
    { m: "un musicien", f: "une musicienne", en: "a musician", kind: "noun" },
    { m: "un opéra", f: "une comédie", en: "an opera / a comedy", kind: "noun" },
    { m: "génial", f: "géniale", en: "great / awesome", kind: "adj" },
    { m: "ennuyeux", f: "ennuyeuse", en: "boring", kind: "adj" },
    { m: "drôle", f: "drôle", en: "funny", kind: "adj" },
  ],
  "4-14": [
    { m: "un café", f: "une bière", en: "a coffee / a beer", kind: "noun" },
    { m: "un thé", f: "une eau (minérale)", en: "a tea / a (mineral) water", kind: "noun" },
    { m: "un jus", f: "une limonade", en: "a juice / a lemonade", kind: "noun" },
    { m: "un sandwich", f: "une salade", en: "a sandwich / a salad", kind: "noun" },
    { m: "un serveur", f: "une serveuse", en: "a waiter / a waitress", kind: "noun" },
    { m: "froid", f: "froide", en: "cold", kind: "adj" },
    { m: "chaud", f: "chaude", en: "hot", kind: "adj" },
    { m: "sucré", f: "sucrée", en: "sweet / sugary", kind: "adj" },
  ],
  "4-15": [
    { m: "un cadeau", f: "une carte", en: "a gift / a card", kind: "noun" },
    { m: "un parfum", f: "une fleur", en: "a perfume / a flower", kind: "noun" },
    { m: "un bijou", f: "une bague", en: "a piece of jewellery / a ring", kind: "noun" },
    { m: "ce", f: "cette", en: "this (demonstrative)", kind: "adj" },
    { m: "vert", f: "verte", en: "green", kind: "adj" },
    { m: "rouge", f: "rouge", en: "red", kind: "adj" },
    { m: "violet", f: "violette", en: "purple", kind: "adj" },
    { m: "doux", f: "douce", en: "soft / sweet", kind: "adj" },
  ],
  "4-16": [
    { m: "un fruit", f: "une pomme", en: "a fruit / an apple", kind: "noun" },
    { m: "un légume", f: "une tomate", en: "a vegetable / a tomato", kind: "noun" },
    { m: "un melon", f: "une fraise", en: "a melon / a strawberry", kind: "noun" },
    { m: "un kilo", f: "une livre", en: "a kilo / a pound", kind: "noun" },
    { m: "un marchand", f: "une marchande", en: "a merchant / vendor", kind: "noun" },
    { m: "frais", f: "fraîche", en: "fresh", kind: "adj" },
    { m: "mûr", f: "mûre", en: "ripe", kind: "adj" },
    { m: "délicieux", f: "délicieuse", en: "delicious", kind: "adj" },
  ],
};
